# Generated by Django 2.2.2 on 2019-06-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fraudDetector', '0002_auto_20190619_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiry_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='last_four_digits',
            field=models.CharField(max_length=4),
        ),
    ]
