# Generated by Django 2.2.2 on 2019-06-20 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fraudDetector', '0003_auto_20190619_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discount_code',
        ),
    ]
